version: '3'
services:
  ximera:
    build: .
    ports:
    - "2000:2000"
    links:
    - redis
    - mongo
    environment:
      - PORT=2000
      - XIMERA_MONGO_URL=mongo
      - XIMERA_REDIS_URL=redis
    volumes:
      - repos:/usr/var/repositories
  redis:
    image: redis
    ports:
    - "6379:6379"
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=ximera
    ports:
     - "27017:27017"
    volumes:
     - mongodata:/data/db
volumes:
  repos:
  mongodata:

